/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.35).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package at.fhtw.swen3.services;

import at.fhtw.swen3.services.dto.HopDTO;
import at.fhtw.swen3.services.dto.WarehouseDTO;
import at.fhtw.swen3.services.dto.ErrorDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "at.fhtw.swen3.codegen.v3.generators.java.SpringCodegen", date = "2022-09-18T11:41:55.463Z[GMT]")
@Validated
public interface WarehouseApi {

    @Operation(summary = "Exports the hierarchy of Warehouse and Truck objects. ", description = "", tags={ "warehouse-management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful response", content = @Content(mediaType = "application/json", schema = @Schema(implementation = WarehouseDTO.class))),
        
        @ApiResponse(responseCode = "400", description = "The operation failed due to an error.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDTO.class))),
        
        @ApiResponse(responseCode = "404", description = "No hierarchy loaded yet.") })
    @RequestMapping(value = "/warehouse",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<WarehouseDTO> exportWarehouses();


    @Operation(summary = "Get a certain warehouse or truck by code", description = "", tags={ "warehouse-management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful response", content = @Content(mediaType = "application/json", schema = @Schema(implementation = HopDTO.class))),
        
        @ApiResponse(responseCode = "400", description = "The operation failed due to an error.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDTO.class))),
        
        @ApiResponse(responseCode = "404", description = "No hop with the specified id could be found.") })
    @RequestMapping(value = "/warehouse/{code}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<HopDTO> getWarehouse(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("code") String code);


    @Operation(summary = "Imports a hierarchy of Warehouse and Truck objects. ", description = "", tags={ "warehouse-management" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successfully loaded."),
        
        @ApiResponse(responseCode = "400", description = "The operation failed due to an error.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDTO.class))) })
    @RequestMapping(value = "/warehouse",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> importWarehouses(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody WarehouseDTO body);

}

